server:
  port: 8081  # 客户端1端口
  servlet:
    context-path: /client1  # 客户端1上下文路径

spring:
  application:
    name: cas-client-1  # 应用名称
  thymeleaf:
    cache: false  # 禁用模板缓存，便于开发
  security:
    filter:
      order: 1  # 安全过滤器顺序

  redis:
    host: localhost
    port: 6379
    password:

# CAS配置
cas:
  # CAS服务器地址 http://171.7.4.234
  server-url-prefix: http://171.7.4.234:8080/cas
  # CAS服务器登录URL
  server-login-url: ${cas.server-url-prefix}/login
  # CAS服务器用户校验URL
  server-valid-url: ${cas.server-url-prefix}/p3/serviceValidate
  # CAS服务器登出URL
  server-logout-url: ${cas.server-url-prefix}/logout
  # 客户端地址，用于CAS服务器回调
  client-host-url: http://localhost:${server.port}${server.servlet.context-path}
  # 验证类型
  validation-type: CAS3

logging:
  level:
    org.springframework.security: DEBUG  # 安全相关日志级别
    org.jasig.cas: DEBUG  # CAS客户端日志级别