# Mysql数据库
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.85:5432/pciis
    username: postgres
    password: tazh_pgsql_2021

    # 连接池大小根据实际情况调整
    max-active: 100
    max-pool-prepared-statement-per-connection-size: 100
  kafka:
    bootstrap-servers: 192.168.2.52:19092
    producer:
      retries: 3
    consumer:
      group-id: pciis-consumer-group

node-system:
  kafka:
    app-id: app-id
    app-secret-key: app-secret-key
    node-code: RZJD

perimeter-intrusion:
  host: localhost
  port: 9581

# 视频流媒体服务配置
video-stream-media:
  host: 192.168.11.137
  port: 8080
  connect-timeout: 5000
  read-timeout: 30000

broadcast:
  host: 171.7.4.1
  port: 81
  username: admin
  password: Gb.123456

devops:
  serverHost: http://192.168.31.58:12909
  project-unique-code: Y4JdNfsfS2tjAQouFm1t035IAnsjSKG3
  project-interaction-secret-key: QBAttyH2ZkolwtkDcn0Y5b8HLGHEtOHC

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

sys:
  config:
    datimsien:
      serviceBaseURL: http://localhost:9580/api/datimsienmock
      user: admin
      password: 123456
      websocketURL: ws://localhost:9580/mockwebsocket

video:
  zlmediakit:
    server: http://localhost:80
    app: live
    vhost: __defaultVhost__
    secret: hGqwJMifJloOX2ZFoqD9ZyhfM4wIIwc2
  livegbs:
    server: http://localhost:10000
    username: admin
    password: admin123